/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.body;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class MessageModelConstants {

  public static final java.lang.String EXAM_NOTICE = "有新的考试《【：考试】》邀请您参加！";

  public static final java.lang.String EXAM_CANCEL_NOTICE = "考试《【：考试】》已取消！";

  public static final java.lang.String TRAIN_NOTICE_ONLINE = "线上培训《【：培训】》邀请您参加！";

  public static final java.lang.String TRAIN_NOTICE_OFFLINE = "线下培训《【：培训】》邀请您参加！";

  public static final java.lang.String TRAIN_PERMIT_NOTICE_ONLINE = "【：部门】-【：姓名】邀请您审核线上培训《【：培训】》";

 // public static final java.lang.String TRAIN_PERMIT_NOTICE_REFUSE_ONLINE = "您申请审核的线上培训《【：培训】》审核未通过";

  public static final java.lang.String TRAIN_PERMIT_NOTICE_OFFLINE = "【：部门】-【：姓名】邀请您审核线下培训《【：培训】》";

 // public static final java.lang.String TRAIN_PERMIT_NOTICE_REFUSE_OFFLINE = "您申请审核的线下培训《【：培训】》审核未通过";

}
