/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ExamScorePhase implements org.apache.thrift.TEnum {
  PhaseOne(100),
  PhaseTwo(90),
  PhaseThree(80),
  PhaseFour(70),
  PhaseFive(60);

  private final int value;

  private ExamScorePhase(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExamScorePhase findByValue(int value) { 
    switch (value) {
      case 100:
        return PhaseOne;
      case 90:
        return PhaseTwo;
      case 80:
        return PhaseThree;
      case 70:
        return PhaseFour;
      case 60:
        return PhaseFive;
      default:
        return null;
    }
  }
}
