/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ExercisesType implements org.apache.thrift.TEnum {
  SingleSelection(1),
  MultipleSelection(2),
  Judgment(3),
  ShortAnswer(4);

  private final int value;

  private ExercisesType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExercisesType findByValue(int value) { 
    switch (value) {
      case 1:
        return SingleSelection;
      case 2:
        return MultipleSelection;
      case 3:
        return Judgment;
      case 4:
        return ShortAnswer;
      default:
        return null;
    }
  }
}
