/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.common.define;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MascotMessageType implements org.apache.thrift.TEnum {
  Notice(1),
  BbsNotice(2),
  ExamNotice(3),
  TrainNotice(4),
  TrainPermitNotice(5);

  private final int value;

  private MascotMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MascotMessageType findByValue(int value) { 
    switch (value) {
      case 1:
        return Notice;
      case 2:
        return BbsNotice;
      case 3:
        return ExamNotice;
      case 4:
        return TrainNotice;
      case 5:
        return TrainPermitNotice;
      default:
        return null;
    }
  }
}
